name: Publish Ana to GitHub Packages

on:
  push

permissions:
  packages: write  # Required to publish to GitHub Packages
  contents: read   # Required to access repository contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build the package
      run: |
        python -m build  # This builds both the source distribution and wheel
        ls dist/  # List the files in the dist directory to verify they were built

    - name: Publish to GitHub Packages
      run: |
        pip install twine
        twine upload --repository-url https://upload.pypi.org/legacy/ dist/*
      env:
        TWINE_USERNAME: "__token__"  # Use the GitHub actor (username)
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
